#THIS FILE WILL BE THE MAIN DOCKER IMAGE BUILD FILE
#MAKE SURE TO READ DOCKER DOCUMENTATION (https://docs.docker.com/engine/reference/builder/)

#WE WILL USE OPENJDK FOR JAVA JVM TO RUN ON
FROM openjdk:7
